serviceTree:
  landscape: &landscape entei
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

cluster: *cluster

loki: https://logs-prod-020.grafana.net/loki/api/v1/push

tempo: https://tempo-prod-14-prod-ap-southeast-1.grafana.net/tempo

mimir: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push

apps:
  target-allocator:
    spec:
      mode: statefulset
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
      podAnnotations:
        <<: *tags

  otlp:
    spec:
      mode: daemonset
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 0m
          memory: 0Mi
      podAnnotations:
        <<: *tags

  otlp-logs:
    spec:
      mode: daemonset
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 0m
          memory: 0Mi
      podAnnotations:
        <<: *tags

  kubelet-stats:
    spec:
      mode: daemonset
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 0m
          memory: 0Mi
      podAnnotations:
        <<: *tags

  container-logs:
    spec:
      mode: daemonset
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 250m
          memory: 1Gi
      podAnnotations:
        <<: *tags

  k8s-cluster:
    collector: k8s-cluster.yaml
    spec:
      mode: deployment
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi
      podAnnotations:
        <<: *tags

  k8s-events:
    spec:
      mode: deployment
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi
      podAnnotations:
        <<: *tags


