# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  platform: &platform sulfoxide
  service: &service silicon
  layer: &layer "1"

# -- Kubernetes labels and annotations, following Service Tree
tags: &tags
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  atomi.cloud/platform: *platform
  atomi.cloud/service: *service
  atomi.cloud/layer: *layer

# -- Landscape the operator is deployed to
landscape: entei

# -- Cluster the operators are deployed to
cluster: opal

# -- Open Observe Endpoint
o2Endpoint: "https://api.openobserve.ai/api/atomicloud_MwvsSHPiOT9uFdn/"

# -- Grafana Cloud Loki Endpoint
lokiEndpoint: "https://logs-prod-020.grafana.net/loki/api/v1/push"

# -- Grafana Cloud Tempo Endpoint
tempoEndpoint: "https://otlp-gateway-prod-ap-southeast-1.grafana.net/otlp"

# -- Name of the common config map to propagate to all collectors
configMapName: &configMapName otel-common-config-map

# -- Configuration for Target Allocator
ta:

  # -- Enable creation of target allocator roles
  createRole: true
  # -- Service account for target allocation
  serviceAccount:
    # -- Enable creation of the service account
    create: true
    # -- Name of the service account
    name: &taSA otel-collector-ta-sa

# -- Configuration for K8S Event Collector
k8sevents:
  # -- Enable creation of k8s events role
  createRole: true
  # -- Service account for k8s events
  serviceAccount:
    # -- Enable creation of the service account
    create: true
    # -- Name of the service account
    name: &k8seventsSA otel-collector-k8sevents-sa

# -- Configuration for K8S Cluster Collector
k8scluster:
  # -- Enable creation of k8s cluster role
  createRole: true
  # -- Service account for k8s cluster
  serviceAccount:
    # -- Enable creation of the service account
    create: true
    # -- Name of the service account
    name: &k8sclusterSA otel-collector-k8scluster-sa

# -- Configuration for Kubelet Collector
kubelet:
  # -- Enable creation of kubelet role
  createRole: true
  # -- VCluster Compatibility
  vclusterCompatibility: false
  # -- Service account for kubelet
  serviceAccount:
    # -- Enable creation of the service account
    create: true
    # -- Name of the service account
    name: &kubeletSA otel-collector-kubelet-sa


#-- Configuration of OTLP Collector
otlp:
  # -- Service account for OTLP
  serviceAccount:
    # -- Enable creation of the service account
    create: true
    # -- Name of the service account
    name: &otlpSA otel-collector-otlp-sa

containerLogs:
  # -- Service account for Container Logs
  serviceAccount:
    # -- Enable creation of the service account
    create: true
    # -- Name of the service account
    name: &containerLogsSA otel-container-logs-sa

# -- Configuration for k8sattr extension
k8sattr:
  # -- Enable creation k8sattr role
  createRole: true
  # -- Service accounts to bind the k8sattr roles to
  bind:
    - *kubeletSA
    - *otlpSA
    - *containerLogsSA
    - *k8sclusterSA
    - *taSA


# -- Create SecretStore via secret of secrets pattern
sulfoxide-bromine:
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  # -- Store name to create
  storeName: doppler-silicon
  # -- Secret of Secrets reference
  rootSecret:
    # -- DOPPLER Token Reference
    ref: "SULFOXIDE_SILICON"

# -- Secret Annotations (External Secrets) to control synchronization
secretAnnotation:
  argocd.argoproj.io/sync-wave: "-2"

# -- Auth configuration for the collectors
auth:
  # -- Name of the secret to use for the collector
  secretName: &secretName o2-cloud-secrets
  # -- Remote Tokens
  remote:
    # -- OpenObserve Token
    o2: MANUAL_O2_TOKEN
    loki:
      # -- Grafana Cloud Loki User
      user: MANUAL_LOKI_USER
      # -- Grafana Cloud Loki Token
      token: MANUAL_LOKI_TOKEN
    tempo:
      # -- Grafana Cloud Tempo User
      user: MANUAL_TEMPO_USER
      # -- Grafana Cloud Tempo Token
      token: MANUAL_TEMPO_TOKEN

  # -- Use internal auth for the collectors (hard coded password)
  internal:
    # -- Enable internal auth
    enable: false
    # -- OpenObserve plaintext token
    o2: sometoken
    # -- Grafana Cloud Loki plaintext user
    loki:
      # -- Grafana Cloud Loki plaintext user
      user: someuser
      # -- Grafana Cloud Loki plaintext token
      token: sometoken
    # -- Grafana Cloud Tempo plaintext user
    tempo:
      # -- Grafana Cloud Tempo plaintext user
      user: someuser
      # -- Grafana Cloud Tempo plaintext token
      token: sometoken
  # -- Use external auth for the collectors
  external:
    # -- Enable external auth
    enable: true
    # -- Secret Store to use for secrets
    secretStore:
      # -- Name of the secret store
      name: doppler-silicon
      # -- Kind of the secret store, either `ClusterSecretStore` or `SecretStore`
      kind: SecretStore
    # -- External Secret Policy
    policy:
      # -- External Secret Creation Policy
      creation: Owner
      # -- External Secret Deletion Policy
      deletion: Retain

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true
# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

# -- Dictionary of collectors to deploy. Key is the name of the collector, while the value is the configuration for the collector.
# This has 2 sub keys: `collector` which is the actual [collector configuration](https://opentelemetry.io/docs/collector/configuration/),
# and `spec`, which is the [operator's configuration](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspec)
# for the collector.
apps:
  target-allocator:
    enable: true
    collector: ta.yaml
    spec:
      mode: statefulset
      targetAllocator:
        enabled: true
        serviceAccount: *taSA
        prometheusCR:
          enabled: true
      serviceAccount: *taSA
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
      podAnnotations:
        <<: *tags
        atomi.cloud/module: target-allocator-collector
        drop_log: "true"
      envFrom:
        - secretRef:
            name: *secretName
        - configMapRef:
            name: *configMapName
      podSecurityContext:
        <<: *podSecurityContext
      securityContext:
        <<: *securityContext

  otlp:
    enable: true
    collector: otlp.yaml
    spec:
      mode: daemonset
      env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      serviceAccount: *otlpSA
      ports:
        - port: 55679
          targetPort: 55679
          name: zpages
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 128Mi
      podAnnotations:
        <<: *tags
        atomi.cloud/module: otlp-collector
        drop_log: "true"
      envFrom:
        - secretRef:
            name: *secretName
        - configMapRef:
            name: *configMapName
      podSecurityContext:
        <<: *podSecurityContext
      securityContext:
        <<: *securityContext

  kubelet-stats:
    enable: true
    collector: kubelet-stats-node-name.yaml
    spec:
      mode: daemonset
      serviceAccount: *kubeletSA
      ports:
        - port: 55679
          targetPort: 55679
          name: zpages
      env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 128Mi
      podAnnotations:
        <<: *tags
        atomi.cloud/module: kubelet-stats-collector
        drop_log: "true"
      envFrom:
        - secretRef:
            name: *secretName
        - configMapRef:
            name: *configMapName
      podSecurityContext:
        <<: *podSecurityContext
      securityContext:
        <<: *securityContext

  container-logs:
    enable: true
    collector: container-logs.yaml
    spec:
      mode: daemonset
      env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      serviceAccount: *containerLogsSA
      ports:
        - port: 55679
          targetPort: 55679
          name: zpages
      podAnnotations:
        <<: *tags
        atomi.cloud/module: container-logs-collector
        drop_log: "true"
      envFrom:
        - secretRef:
            name: *secretName
        - configMapRef:
            name: *configMapName
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 256Mi
      volumeMounts:
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
      podSecurityContext:
        runAsNonRoot: false
      securityContext: { }

  k8s-cluster:
    enable: true
    collector: k8s-cluster.yaml
    spec:
      mode: deployment
      ports:
        - port: 55679
          targetPort: 55679
          name: zpages
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi
      serviceAccount: *k8sclusterSA
      podAnnotations:
        <<: *tags
        atomi.cloud/module: cluster-metrics-collector
        drop_log: "true"
      envFrom:
        - secretRef:
            name: *secretName
        - configMapRef:
            name: *configMapName
      podSecurityContext:
        <<: *podSecurityContext
      securityContext:
        <<: *securityContext

  k8s-events:
    enable: true
    collector: k8s-events.yaml
    spec:
      mode: deployment
      ports:
        - port: 55679
          targetPort: 55679
          name: zpages
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi
      serviceAccount: *k8seventsSA
      podAnnotations:
        <<: *tags
        atomi.cloud/module: cluster-events-collector
        drop_log: "true"
      envFrom:
        - secretRef:
            name: *secretName
        - configMapRef:
            name: *configMapName
      podSecurityContext:
        <<: *podSecurityContext
      securityContext:
        <<: *securityContext


