serviceTree:
  landscape: &landscape pikachu
  cluster: &cluster opal

tags: &tags
  atomi.cloud/landscape: *landscape
  atomi.cloud/cluster: *cluster

landscape: *landscape
cluster: *cluster

taEndpoint: pikachu-silicon-target-allocator-targetallocator

sulfoxide-bromine:
  serviceTree:
    landscape: *landscape
    cluster: *cluster

apps:

  otlp:
    enable: false

  container-logs:
    enable: false

  target-allocator:
    spec:
      mode: statefulset
      replicas: 1
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 125m
          memory: 128Mi
      podAnnotations:
        <<: *tags

  kubelet-stats:
    spec:
      mode: daemonset
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: "0"
          memory: "0"
      podAnnotations:
        <<: *tags

  k8s-cluster:
    collector: k8s-cluster.yaml
    spec:
      mode: deployment
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi
      podAnnotations:
        <<: *tags

  # done
  k8s-events:
    spec:
      mode: deployment
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi
      podAnnotations:
        <<: *tags


