serviceTree:
  landscape: pichu
  cluster: opal
  platform: systems
  service: telemetry-collector
  layer: "1"

cluster: pichu-opal

apps:
  target-allocator:
    collector: ta.yaml
    spec:
      mode: statefulset
      podAnnotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
  otlp:
    collector: otlp.yaml
    spec:
      mode: daemonset
      podAnnotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 128Mi

  otlp-logs:
    collector: otlp-logs.yaml
    spec:
      mode: daemonset
      podAnnotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 128Mi

  kubelet-stats:
    collector: kubelet-stats.yaml
    spec:
      mode: daemonset
      podAnnotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 128Mi

  container-logs:
    collector: container-logs.yaml
    spec:
      mode: daemonset
      podAnnotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 256Mi
  k8s-cluster:
    collector: k8s-cluster.yaml
    spec:
      mode: deployment
      podAnnotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi

  k8s-events:
    collector: k8s-events.yaml
    spec:
      mode: deployment
      podAnnotations:
        atomi.cloud/landscape: pichu
        atomi.cloud/cluster: opal
      replicas: 1
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 256Mi

auth:
  secretName: grafana-cloud-secrets
  mimir:
    user:
      local: MIMIR_USER
      remote: MIMIR_USER
    password:
      local: MIMIR_PASSWORD
      remote: MIMIR_PASSWORD
  loki:
    user:
      local: LOKI_USER
      remote: LOKI_USER
    password:
      local: LOKI_PASSWORD
      remote: LOKI_PASSWORD
  tempo:
    user:
      local: TEMPO_USER
      remote: TEMPO_USER
    password:
      local: TEMPO_PASSWORD
      remote: TEMPO_PASSWORD
  internal:
    enable: false
    mimir:
      user: ""
      password: ""
    loki:
      user: ""
      password: ""
    tempo:
      user: ""
      password: ""
  external:
    enable: true
    remoteSecretName: /pichu/grafana_cloud/token
    secretStore:
      name: aws-ssm-secret-store
      kind: ClusterSecretStore
    policy:
      creation: Owner
      deletion: Retain
