{{ if .Values.coredns.patch }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    kubeapi
    kubenodes {{ .Values.coredns.baseDomain | default "node.cluster.local" }} in-addr.arpa ip6.arpa {
      fallthrough in-addr.arpa ip6.arpa
    }
{{- end }}