{{- if .Values.k8sattr.createRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-otel-k8s-attr"
  labels:
    {{- include "atomi-otel-collectors.labels" .  | nindent 4 }}
  annotations:
    {{- include "atomi-otel-collectors.annotations" .  | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
{{- end -}}
{{- range $v := .Values.k8sattr.bind  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $v }}-k8s-attr
  labels:
      {{- include "atomi-otel-collectors.labels" $ | nindent 4 }}
  annotations:
    {{- include "atomi-otel-collectors.annotations" $  | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ $.Release.Name }}-otel-k8s-attr"
subjects:
  - kind: ServiceAccount
    name: {{ $v }}
    namespace: {{ $.Release.Namespace }}
---
{{- end -}}
