{{- if .Values.k8sevents.createRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{.Release.Name }}-opentelemetry-k8s-events-role"
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name }}-opentelemetry-k8s-events-cr-rolebinding
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{.Release.Name }}-opentelemetry-k8s-events-role"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.k8sevents.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if .Values.k8sevents.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
  name: {{ .Values.k8sevents.serviceAccount.name }}
{{- end -}}
