{{- if .Values.k8scluster.createRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-otel-k8s-cluster"
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
{{- end -}}
{{- if and .Values.k8scluster.createRole .Values.k8scluster.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name }}-otel-k8s-cluster
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-otel-k8s-cluster"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.k8scluster.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.k8scluster.serviceAccount.name }}
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
{{- end -}}
