{{- if .Values.kubelet.createRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-otel-kubelet"
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
---
{{- end -}}
{{- if and .Values.kubelet.createRole .Values.kubelet.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name }}-otel-kubelet
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-otel-kubelet"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubelet.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.kubelet.vclusterCompatibility }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name }}-otel-kubelet-delegate-auth
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:auth-delegator"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubelet.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kubelet.serviceAccount.name }}
  labels:
      {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations:
    {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
{{- end -}}
