{{ range $k, $v := .Values.apps }}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ $.Release.Name }}-{{ $k }}
  labels: {{- include "sulfoxide-silicon.labels" $  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" $  | nindent 4 }}
spec:
  {{ $v.spec | toYaml | nindent 2 }}
  config: |
    {{ $.Files.Get (printf "%s/%s" "collectors" $v.collector ) | nindent 4 }}
---
{{ end }}
