apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
data:
  CLUSTER: "{{ .Values.cluster }}"
  MIMIR_ENDPOINT: "{{ .Values.mimir }}"
  LOKI_ENDPOINT: "{{ .Values.loki }}"
  TEMPO_ENDPOINT: "{{ .Values.tempo }}"
