apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
data:
  K8S_LANDSCAPE: "{{ .Values.landscape }}"
  K8S_CLUSTER: "{{ .Values.cluster }}"
  TA_ENDPOINT: "{{ .Values.taEndpoint }}"
  O2_ENDPOINT: "{{ .Values.o2Endpoint }}"
  LOKI_ENDPOINT: "{{ .Values.lokiEndpoint }}"

