{{- if .Values.otlp.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
  name: {{ .Values.otlp.serviceAccount.name }}
{{- end -}}
---
{{- if .Values.containerLogs.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "sulfoxide-silicon.labels" .  | nindent 4 }}
  annotations: {{- include "sulfoxide-silicon.annotations" .  | nindent 4 }}
  name: {{ .Values.containerLogs.serviceAccount.name }}
{{- end -}}