receivers:
  k8s_events:

exporters:
  loki:
    endpoint: ${env:LOKI_ENDPOINT}
    auth:
      authenticator: basicauth/loki

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679
  basicauth/loki:
    client_auth:
      username: ${env:LOKI_USER}
      password: ${env:LOKI_TOKEN}

processors:
  batch:
  attributes:
    actions:
      - key: otel.source
        action: insert
        value: k8s-events
      - action: insert
        key: loki.attribute.labels
        value: otel.source, k8s.namespace.name
  resource:
    attributes:
      - key: k8s.landscape
        action: insert
        value: ${env:K8S_LANDSCAPE}
      - key: k8s.cluster
        action: insert
        value: ${env:K8S_CLUSTER}
      - action: insert
        key: loki.resource.labels
        value: >-
          k8s.cluster

service:
  extensions: [ health_check, pprof, zpages, basicauth/loki ]
  pipelines:
    logs:
      receivers: [ k8s_events ]
      processors: [ batch, attributes, resource ]
      exporters: [ loki ]
