receivers:
  k8s_cluster:
    collection_interval: 30s
    node_conditions_to_report:
      - Ready
      - MemoryPressure
      - DiskPressure
      - PIDPressure
      - NetworkUnavailable
    allocatable_types_to_report:
      - cpu
      - memory
      - ephemeral-storage
      - storage

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s
  attributes:
    actions:
      - key: container.id
        action: delete
      - key: otel.source
        action: insert
        value: k8s-cluster
      - key: k8s.deployment.uid
        action: delete
      - key: k8s.hpa.uid
        action: delete
      - key: k8s.namespace.uid
        action: delete
      - key: k8s.node.uid
        action: delete
      - key: k8s.pod.uid
        action: delete
      - key: k8s.replicaset.uid
        action: delete
      - key: k8s.statefulset.uid
        action: delete
  resource:
    attributes:
      - key: container.id
        action: delete
      - key: k8s.landscape
        action: insert
        value: ${env:K8S_LANDSCAPE}
      - key: k8s.cluster
        action: insert
        value: ${env:K8S_CLUSTER}
      - key: k8s.deployment.uid
        action: delete
      - key: k8s.hpa.uid
        action: delete
      - key: k8s.namespace.uid
        action: delete
      - key: k8s.node.uid
        action: delete
      - key: k8s.pod.uid
        action: delete
      - key: k8s.replicaset.uid
        action: delete
      - key: k8s.statefulset.uid
        action: delete
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.daemonset.name
        - k8s.statefulset.name
        - k8s.replicaset.name
        - k8s.job.name
        - k8s.cronjob.name
        - k8s.namespace.name
        - k8s.node.name
      annotations:
        - tag_name: drop_log
          key: drop_log
          from: pod
        - tag_name: landscape
          key: atomi.cloud/landscape
          from: pod
        - tag_name: cluster
          key: atomi.cloud/cluster
          from: pod
        - tag_name: platform
          key: atomi.cloud/platform
          from: pod
        - tag_name: module
          key: atomi.cloud/module
          from: pod
        - tag_name: service
          key: atomi.cloud/service
          from: pod
      labels:
        - tag_name: landscape
          key: atomi.cloud/landscape
          from: pod
        - tag_name: cluster
          key: atomi.cloud/cluster
          from: pod
        - tag_name: service
          key: atomi.cloud/service
          from: pod
        - tag_name: platform
          key: atomi.cloud/platform
          from: pod
        - tag_name: module
          key: atomi.cloud/module
          from: pod
        - tag_name: drop_log
          key: drop_log
          from: pod
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.uid
  filter/drop_vcluster:
    metrics:
      metric:
        - 'IsMatch(resource.attributes["k8s.namespace.name"],"(pichu|pikachu|raichu)")'

exporters:
  otlphttp/openobserve:
    endpoint: ${env:O2_ENDPOINT}
    headers:
      Authorization: Basic ${env:O2_AUTH}

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages ]
  pipelines:
    metrics:
      receivers: [k8s_cluster]
      processors: [ k8sattributes, resource, attributes, filter/drop_vcluster, batch]
      exporters: [otlphttp/openobserve] # mimir
