receivers:
  k8s_events:

exporters:
  logging:
  otlphttp/openobserve_k8s_events:
    endpoint: ${env:O2_ENDPOINT}
    headers:
      Authorization: Basic ${env:O2_AUTH}
      stream-name: k8s_events

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

processors:
  batch:
  attributes:
    actions:
      - key: otel.source
        action: insert
        value: k8s-events
  resource:
    attributes:
      - key: k8s.landscape
        action: insert
        value: ${env:K8S_LANDSCAPE}
      - key: k8s.cluster
        action: insert
        value: ${env:K8S_CLUSTER}

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    logs:
      receivers: [ k8s_events ]
      processors: [ batch, attributes, resource ]
      exporters: [ otlphttp/openobserve_k8s_events ]
