receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
    send_batch_size: 10000
    timeout: 10s
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      node_from_env_var: KUBE_NODE_NAME
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.daemonset.name
        - k8s.statefulset.name
        - k8s.replicaset.name
        - k8s.job.name
        - k8s.cronjob.name
        - k8s.namespace.name
        - k8s.node.name
      annotations:
        - tag_name: drop_log
          key: drop_log
          from: pod
        - tag_name: landscape
          key: atomi.cloud/landscape
          from: pod
        - tag_name: cluster
          key: atomi.cloud/cluster
          from: pod
        - tag_name: platform
          key: atomi.cloud/platform
          from: pod
        - tag_name: module
          key: atomi.cloud/module
          from: pod
        - tag_name: service
          key: atomi.cloud/service
          from: pod
      labels:
        - tag_name: landscape
          key: atomi.cloud/landscape
          from: pod
        - tag_name: cluster
          key: atomi.cloud/cluster
          from: pod
        - tag_name: service
          key: atomi.cloud/service
          from: pod
        - tag_name: platform
          key: atomi.cloud/platform
          from: pod
        - tag_name: module
          key: atomi.cloud/module
          from: pod
        - tag_name: drop_log
          key: drop_log
          from: pod
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.ip
      - sources:
          - from: resource_attribute
            name: k8s.pod.uid
      - sources:
          - from: connection
  attributes:
    actions:
      - key: container.id
        action: delete
      - key: otel.source
        action: insert
        value: otlp

  resource:
    attributes:
      - key: container.id
        action: delete

exporters:
  otlphttp/openobserve:
    endpoint: ${env:O2_ENDPOINT}
    headers:
      Authorization: Basic ${env:O2_AUTH}

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ k8sattributes, resource, attributes, batch ]
      exporters: [ otlphttp/openobserve ]
    traces:
      receivers: [ otlp ]
      processors: [ k8sattributes, resource, attributes, batch ]
      exporters: [ otlphttp/openobserve ]
    metrics:
      receivers: [ otlp ]
      processors: [ k8sattributes, resource, attributes, batch ]
      exporters: [ otlphttp/openobserve ]
